---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: Customer
  labels:
    app: Customer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: Customer
  template:
    metadata:
      labels:
        app: Customer
    spec:
      containers:
        - name: Customer
          image: username/Customer:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: View
  labels:
    app: View
spec:
  replicas: 1
  selector:
    matchLabels:
      app: View
  template:
    metadata:
      labels:
        app: View
    spec:
      containers:
        - name: View
          image: username/View:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: Reservation
  labels:
    app: Reservation
spec:
  replicas: 1
  selector:
    matchLabels:
      app: Reservation
  template:
    metadata:
      labels:
        app: Reservation
    spec:
      containers:
        - name: Reservation
          image: username/Reservation:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: Vaccine
  labels:
    app: Vaccine
spec:
  replicas: 1
  selector:
    matchLabels:
      app: Vaccine
  template:
    metadata:
      labels:
        app: Vaccine
    spec:
      containers:
        - name: Vaccine
          image: username/Vaccine:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5


---


apiVersion: v1
kind: Service
metadata:
  name: Customer
  labels:
    app: Customer
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: Customer


---


apiVersion: v1
kind: Service
metadata:
  name: View
  labels:
    app: View
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: View


---


apiVersion: v1
kind: Service
metadata:
  name: Reservation
  labels:
    app: Reservation
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: Reservation


---


apiVersion: v1
kind: Service
metadata:
  name: Vaccine
  labels:
    app: Vaccine
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: Vaccine

